### ISSUE TITLE
position: absolute

### ISSUE THREAD

**Issue by bunzli** [platanus/angular-pretty-load#2]
Si uso lo siguiente se rompe el pretty load.

``` css
img {
    position: absolute;
    top: 10px;
    left: 30px;
}
```

Habría que pensar como hacer para que el wrapper entienda esas propiedades... o agregar en el readme como resolver esto...
